/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Order.Order;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dhaval
 */
public class CustomerReviewJPanel extends javax.swing.JPanel {
    private JPanel userContainer;
    EcoSystem ecoSystem;
    /**
     * Creates new form CustomerReviewJPanel
     */
    public CustomerReviewJPanel(JPanel userContainer,EcoSystem ecoSystem) {
        initComponents();
        this.userContainer = userContainer;
        this.ecoSystem=ecoSystem;
        populateCustomerOrderTable();
    }

    private void populateCustomerOrderTable() {
        DefaultTableModel model = (DefaultTableModel)tblCustomerReview.getModel();
        model.setRowCount(0);
        for (Restaurant restaurant:ecoSystem.getRestaurantDirectory().getRestaurantList())
        {
            for(Order order:restaurant.getOrderList())
            {
                if(order.getStatus().toLowerCase().equals("delivered"))
                {
                    Object[] row = new Object[3];
                    row[0] = order.getRestaurantName();
                    row[1] = order.getCustomerName();
                    row[2] = order.getCustComment();
                    model.addRow(row);
                }
            }     
        } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcustomerReview = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerReview = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcustomerReview.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblcustomerReview.setText("Customer Review : ");
        add(lblcustomerReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 560, 30));

        tblCustomerReview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Restaurant Name", "Customer Name", "Customer Review"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomerReview);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 560, 210));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userContainer.remove(this);
        Component[] componentArray = userContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userContainer.getLayout();
        layout.previous(userContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcustomerReview;
    private javax.swing.JTable tblCustomerReview;
    // End of variables declaration//GEN-END:variables
}
